### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by Odrowaz** [db260179/ps3syscon#1]
I'm getting those 2 error but... what means? Where i should start looking?
A0213013 BE_SPI DI/DO ERROR
A0203010 BE_INIT OR BE_POWGOOD OR CLOCK ERRORS

**Comment by db260179** [comment]
So first off, state what PS3 motherboard it is?

Add your syscon screen log to this ticket full log

Then do some voltage readings - there is a voltage readout expected in the thread you had originally posted - psx-place for the COK-002 board.

If i was to guess, your CELL processor is not happy, either a IC clock is shorted or not working or the cell is not recieving data.
Either way the voltage test points need to be checked before a conculsion is made. At the moment we are all learning the errors and cause and have no straight answer.

In this github repo there is a syscon error codes.pdf, give you an indication on the area to look at.

**Comment by Odrowaz** [comment]
here's the syscon log, the motherboard is "fine" the only thing is the cmos battery  holder was broken i soldered the wire directly in the socket but i get the 3.3v over the diode ( the A0213013 error doesn't apper often) anyway in the pdf file the 3013 error does not exist and the 3010 is a "BE ERROR" oh i forgot the motherboard is a COK-002

>$ bringup
[SSM] state: 0600 -> 0000
[SSM] Error state is cleared.
(PowerOff State)
[SSM] state: 0000 -> 0101
Bringup Mode #0 (0xFF)
[SSM] ssmCb_OnStartingBePowOn() called.
[SSM] Bringup mode : syspm_stat=00000000/00000000
[POWSEQ] PowerSeq_Setup called.
[SSM] state: 0101 -> 0201
[POWSEQ] AV Backend Setup
[SSM] state: 0201 -> 0102
[POWERSEQ] Error : wait attention timeout.(SEQ1)
[SSM] state: 0102 -> 0302
[SSM] PowSeq Fail : Detected !
[SSM] state: 0302 -> 0700
[POWSEQ] AV Backend Letup
[SSM] Shutdown mode : syspm_stat=00000000/00000000
[ERROR]: 0xa0203010
[POWSEQ] PowerSeq_Letup called.
[SSM] state: 0700 -> 0600
(PowerOff State) (Fatal)
[SSM] state: 0600 -> 0000
[SSM] Error state is cleared.
(PowerOff State)
bringup
[SSM] state: 0000 -> 0101
Bringup Mode #0 (0xFF)
[SSM] ssmCb_OnStartingBePowOn() called.
[SSM] Bringup mode : syspm_stat=00000000/00000000
[POWSEQ] PowerSeq_Setup called.
[SSM] state: 0101 -> 0201
[POWSEQ] AV Backend Setup
[SSM] state: 0201 -> 0102
[POWERSEQ] Error : wait attention timeout.(SEQ1)
[SSM] state: 0102 -> 0302
[SSM] PowSeq Fail : Detected !
[SSM] state: 0302 -> 0700
[POWSEQ] AV Backend Letup
[SSM] Shutdown mode : syspm_stat=00000000/00000000
[ERROR]: 0xa0203010
[POWSEQ] PowerSeq_Letup called.
[SSM] state: 0700 -> 0600
(PowerOff State) (Fatal)

**Comment by Odrowaz** [comment]
nice you put the test points in the github code later i will test all the point and put here the result

**Comment by Odrowaz** [comment]
Hi, all the voltage are good as expected but i can't get the error 3013 showing up again only the 3010 and i know for sure that the battery socket was broken... how i check for clock damage?
All the errlog write a clock:0xffffffff can i set a time from the computer? Pressing on gpu/cpu give no difference

**Comment by Odrowaz** [comment]
Ok maybe the cell is dead or i don't know i can get the temperature from rsx and the southbridge but the cell say 0.00

**Comment by db260179** [comment]
So i had a sem-001 board having the same error message 3013. The issue is indeed the CELL processor not communicating to the syscon via the SPI protocol.

Checking the voltage lines around it show up that the 1.2V MC2_VDDIO IC6012 was not being outputed. Which intern lead back to IC6302 not outputting 1.2V BE_VCS. Hard to know if this is fault with the CELL?, but its not talking.
