### ISSUE TITLE
USB device not responding on SEM-01

### ISSUE THREAD

**Issue by majyphi** [db260179/ps3syscon#2]
Hi, 

Not sure if it's the right place to ask, but you seem to have more experience with the system than I have.
I have a SEM-01, currently under YLOD issue.

I've made the wiring of the USB cable, Tx, Rx and Ground (without DIAG for now).

This is the output of `dmesg` :
```
[  228.955107] usb 1-9: new full-speed USB device number 14 using xhci_hcd
[  229.082908] usb 1-9: device descriptor read/64, error -71
[  229.318621] usb 1-9: device descriptor read/64, error -71
[  229.554143] usb 1-9: new full-speed USB device number 15 using xhci_hcd
[  229.682007] usb 1-9: device descriptor read/64, error -71
[  229.917612] usb 1-9: device descriptor read/64, error -71
[  230.029415] usb usb1-port9: attempt power cycle
[  230.680434] usb 1-9: new full-speed USB device number 16 using xhci_hcd
[  230.680596] usb 1-9: Device not responding to setup address.
[  230.888273] usb 1-9: Device not responding to setup address.
[  231.095826] usb 1-9: device not accepting address 16, error -71
[  231.223654] usb 1-9: new full-speed USB device number 17 using xhci_hcd
[  231.223815] usb 1-9: Device not responding to setup address.
[  231.431478] usb 1-9: Device not responding to setup address.
[  231.639064] usb 1-9: device not accepting address 17, error -71
[  231.639147] usb usb1-port9: unable to enumerate USB device
```

I've switched Rx and Tx to check if the issue was coming from there.
Any idea what is the root cause ?

**Comment by db260179** [comment]
Sometimes these usb tty cable dont like usb 3.0 port.

what usb tty cable is it? must be 3.3v, if not working in a usb 2.0 port the. proberly faulty?

**Comment by majyphi** [comment]
Well, thanks for making me double check. I don't have the proper cable, indeed, it was 5v.

I also realized you asked to not raise issues for individual tech support. So thanks again for the trouble.

**Comment by db260179** [comment]
No problem, A lead like this will work - https://www.ebay.co.uk/itm/USB-to-TTL-Serial-Cable-Adapter-FTDI-Chipset-FT232-USB-Cable-FT232BL-TTL-3-3V/163924384568?hash=item262aa79b38:g:iBIAAOSwhQJdXRp6
