### ISSUE TITLE
Update docs on running on Windows

### ISSUE THREAD

**Issue by leonkiriliuk** [db260179/ps3syscon#6]
There are 2 Python libraries that are not installed by default with Python that need to be installed for the standalone python script to work.  This needs to be documented, especially for those running this on a VM with older version of Windows (e.g. I'm running Windows 7)

Once Python is installed, run the following commands to make sure the required libraries are included:
- pip install pyserial
- pip install pycryptodome

**Comment by db260179** [comment]
OK added note in the README.md about this
